# This is a very simple docker compose file that will start the server and mount the
# relevant index.html file so it can be changed locally. 
# Start with `docker-compose up` and then open http://localhost on your machine.

version: '3.7'

services:
  nginx:
    build: .
    volumes:
      - .:/usr/share/nginx/html/
    ports:
      - "80:80"
  