version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     # build the application image
     - run: docker build -t ambientinnovation/nginx-demo:$CIRCLE_BRANCH .

     # push the image
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker push ambientinnovation/nginx-demo:$CIRCLE_BRANCH
