kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysqldataclaim
  namespace: marius
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
